name: MyAuth
author: creeperded14
description: The MyAuth is a plugin based AuthMe, it serves to protect the inventories and the reputation of the player concerned.
main: uk.org.creeperded14.myauth.MyAuth
version: 1.0
commands:
    register:
        description: Register an account
        usage: /register password
    login:
        description: Login into a account
        usage: /login password
    changepassword:
        description: Change password of a account
        usage: /changepassword oldPassword newPassword
    logout:
        description: Logout
        usage: /logout
    unregister:
        description: unregister your account
        usage: /unregister password
    myauth:
        description: MyAuth op commands
        usage: '/myauth reload|register playername password|changepassword playername password|unregister playername'
permissions:
    myauth.*:
        description: Gives access to all myauth commands
        children:
            myauth.register: true
            myauth.login: true
            myauth.changepassword: true
            myauth.logout: true
            myauth.unregister: true
    myauth.admin.*:
         description: Gives access to all myauth admin commands
         children:
             myauth.admin.reload: true
             myauth.admin.register: true
             myauth.admin.changepassword: true
             myauth.admin.unregister: true
             muauth.admin.purge: true
    myauth.register:
        description: Register an account
        default: true
    myauth.login:
        description: Login into a account
        default: true
    myauth.changepassword:
        description: Change password of a account
        default: true
    myauth.logout:
        description: Logout
        default: true
    myauth.unregister:
        description: unregister your account
        default: true
    myauth.admin.reload:
        description: MyAuth reload commands
        default: op
    myauth.admin.register:
        description: MyAuth register command
        default: op
    myauth.admin.changepassword:
        description: MyAuth changepassword command
        default: op
    myauth.admin.unregister:
        description: MyAuth unregister command
        default: op
    myauth.admin.purge:
        description: MyAuth unregister command
        default: op
